layouts:
  - tall
  - wide
  - fullscreen

mod1:
  - option
  - shift

mod2:
  - option
  - shift
  - command

reevaluate-windows:
  mod: mod1
  key: z

toggle-tiling:
  mod: mod1
  key: t

swap-main:
  mod: mod1
  key: enter

mouse-follows-focus: true

use-canary-build: true

screen-padding-left: 12
screen-padding-right: 12
screen-padding-top: 12
screen-padding-bottom: 12

window-margins: true
smart-window-margins: true
window-margin-size: 5

# key bindings
focus-screen-1:
  mod: mod1
  key: 1

focus-screen-2:
  mod: mod1
  key: 2

focus-screen-3:
  mod: mod1
  key: 3

throw-screen-1:
  mod: mod2
  key: 1

throw-screen-2:
  mod: mod2
  key: 2

throw-screen-3:
  mod: mod3
  key: 3

